### ISSUE TITLE
LogPrefix não funcionando

### ISSUE THREAD

**Issue by RuanFernandes** [RuanFernandes/RuServer#1]
O log prefix não funciona, não da pra mudar o prefixo dos logs salvos, nem escolher os niveis de log.

**Comment by mJR-exe** [comment]
Olá, @RuanFernandes. Desejo trabalhar nessa issue.

**Comment by RuanFernandes** [comment]
Opa @mJR-exe, pode dar essa ajuda por favor

**Comment by RuanFernandes** [comment]
Valeuu
